### ISSUE TITLE
出现“ValueError: The number of weights does not match the population”问题

### ISSUE THREAD

**Issue by marico2020** [Little-Podi/GRM#1]
训练代码的时候出现“ValueError: The number of weights does not match the population”，更换numpy的版本也不行，请问您有遇到过这个问题吗？

**Comment by Little-Podi** [comment]
Thanks for letting me know. Could you please provide a more specific error report (such as a screenshot) to show where you encounter this problem? The training code can run smoothly with two different conda environments (NumPy v1.21.3 and v1.23.1) I just tried.

**Comment by marico2020** [comment]
> Thanks for letting me know. Could you please provide a more specific error report (such as a screenshot) to show where you encounter this problem? The training code can run smoothly with two different conda environments (NumPy v1.21.3 and v1.23.1) I just tried.

![image](https://user-images.githubusercontent.com/68038484/231943553-7bd41f8f-8f34-4ec3-9ea0-7075492adcdd.png)
我的numpy换成1.21.3还是会出现这个问题，我的python是3.7版本。

**Comment by Little-Podi** [comment]
这应该不是版本的问题，看上去是因为你的训练数据集准备方式不太一致哈～

**Comment by marico2020** [comment]
![image](https://user-images.githubusercontent.com/68038484/231946540-b58c9cd7-0de5-445f-8b0e-de8c36afac2a.png)
我把numpy换成1.21.3还是不行，python是3.7的版本。

**Comment by marico2020** [comment]
我明白了，之前只测试一个got10k数据集， 忘把DATASETS_RATIO其他数据给注释了， 现在可以跑通了，非常感谢您的帮助！

**Comment by Little-Podi** [comment]
I do not think it is caused by a wrong version of package. It seems to be an inconsistent dataset preparation issue.

**Comment by Little-Podi** [comment]
Great to hear that! You are welcome.
