### ISSUE TITLE
The checkpoints type did not match expectations

### ISSUE THREAD

**Issue by Asa13opp** [Little-Podi/GRM#13]
Try training with trained_model -- GRM_ep0300.pth.tar provided by the author, but keep reporting error that checkpoint type is not the expected type (GRM)
![image](https://github.com/Little-Podi/GRM/assets/149283703/5be3309a-cb7e-4017-8089-8e55d58ae302)
![image](https://github.com/Little-Podi/GRM/assets/149283703/bc23c0c3-6efc-46d0-ae46-4b8c22659401)
![image](https://github.com/Little-Podi/GRM/assets/149283703/65a798be-746b-4459-a9a9-65125cc54d4a)

**Comment by Little-Podi** [comment]
It has been a long time since I posted this code, so I am not quite sure. However, it seems that you are not loading the checkpoint I uploaded but OSTrack's instead.
