### ISSUE TITLE
About train

### ISSUE THREAD

**Issue by CBCBLXM** [Little-Podi/GRM#14]
![image](https://github.com/Little-Podi/GRM/assets/164166921/4b4da3ef-5093-42db-b6e5-36b79b5dddef)
When I train my code, it did not work. How to sove the problem, please?Always stuck in this interface
My environment:
![image](https://github.com/Little-Podi/GRM/assets/164166921/bc5c1650-f4cd-4923-9011-554d72433f92)

**Comment by Little-Podi** [comment]
It is working if it is not being interrupted. You can take a look at the GPU usage to check if the training is running. To make the training log concise, I only print the training status at the end of each epoch. I think you just need to wait for a while to see the next log being printed.
