### ISSUE TITLE
about the calculation of attention mask M

### ISSUE THREAD

**Issue by ElliottZhen** [Little-Podi/GRM#2]
hi, congratulations! great work.
In your papaer ,I'm a little confused about formula 7 

![image](https://user-images.githubusercontent.com/56305119/233581594-7c5fda11-1aa4-4083-9c08-64c36a0151fb.png)

If the Di is tempalte token ,it should be (1,0,0),  and weather the Dj is ES token or EA token , by the 7th formula ,the Mij is zero.

So how do ET and EA interact, refer to the second formula

![image](https://user-images.githubusercontent.com/56305119/233584638-de0c58ca-7339-4b68-b296-697d2947480c.png)

I am looking forward to your reply!Thank you.

**Comment by Little-Podi** [comment]
Hello! There is indeed a typo in equation (7) as the interaction between ET and EA is bidirectional. The corrected formula should be
![image](https://user-images.githubusercontent.com/96873712/233591906-f7770e9b-87d5-4afb-80c9-e454fb6fc7b7.png)
However, the [code implementation](https://github.com/Little-Podi/GRM/blob/9dd3c13ec60948c3dc5fd453d37ef022783f2f20/lib/models/grm/vit.py#L64) is absolutely correct. Sorry for the confusion. It is a little bit embarrassing to have such a mistake survive numerous revisions. Thanks a lot for your carefulness. I will fix the paper on arXiv accordingly.
