### ISSUE TITLE
About computing the mask M

### ISSUE THREAD

**Issue by kun-dragon** [Little-Podi/GRM#5]
In the 'softmax_with_policy' function:
`attn_policy = attn_policy + (1.0 - attn_policy) * eye`
Is the second item (` (1.0 - attn_policy) * eye`)  equal to 0

**Comment by Little-Podi** [comment]
Exactly. I wrote this disturbing line just to make sure every token is always doing self-attention with itself. However, from the logic of the code, the second item seems to be useless anyway. Your finding is correct.

**Comment by kun-dragon** [comment]
Ok, thanks!
